# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 786)
        MainWindow.setMinimumSize(QtCore.QSize(536, 757))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("border:none;")
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget {\n"
"    color: rgb(0, 0, 0); /* Change this line to set text color to black */\n"
"    font: 10.75pt \"Roboto Black\";\n"
"\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bg{    \n"
"}\n"
"\n"
"QLabel{\n"
"color:#AD00BE;\n"
"\n"
"}\n"
"/*\n"
"QPushButton{\n"
"background-color:#B7995D;\n"
"    border-radius:5px;\n"
"padding:5px;\n"
"color:#161616;\n"
"    font:  11pt \"Segoe UI\";\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:#ad854d;\n"
"}\n"
"*/\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;  /* Initially, set a transparent border */\n"
"    padding:3px;\n"
"\n"
"}\n"
"\n"
"#QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);  /* Change the border color when the button is focused/clicked */\n"
"}\n"
"\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(0, 0, 0, 0)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bg = QtWidgets.QFrame(self.styleSheet)
        self.bg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg.setObjectName("bg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bg)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.bg)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.topBar = QtWidgets.QFrame(self.frame_2)
        self.topBar.setMinimumSize(QtCore.QSize(0, 140))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 140))
        self.topBar.setStyleSheet("background-color: #AD00BE;\n"
"")
        self.topBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftSide_2 = QtWidgets.QFrame(self.topBar)
        self.leftSide_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftSide_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftSide_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftSide_2.setObjectName("leftSide_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftSide_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.leftSide_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lblLogo = QtWidgets.QLabel(self.frame_7)
        self.lblLogo.setGeometry(QtCore.QRect(10, 0, 251, 141))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/images/images/logo3.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.btnModel = QtWidgets.QPushButton(self.frame_7)
        self.btnModel.setGeometry(QtCore.QRect(20, 115, 161, 21))
        self.btnModel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModel.setStyleSheet("font: 8pt \"Roboto\";\n"
"color:white;")
        self.btnModel.setAutoDefault(False)
        self.btnModel.setDefault(False)
        self.btnModel.setFlat(True)
        self.btnModel.setObjectName("btnModel")
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_5.addWidget(self.leftSide_2)
        self.rightsSide_2 = QtWidgets.QFrame(self.topBar)
        self.rightsSide_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightsSide_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightsSide_2.setObjectName("rightsSide_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.rightsSide_2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_11 = QtWidgets.QFrame(self.rightsSide_2)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_19.setContentsMargins(-1, 15, 20, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.btnClose = QtWidgets.QPushButton(self.frame_11)
        self.btnClose.setMinimumSize(QtCore.QSize(25, 25))
        self.btnClose.setMaximumSize(QtCore.QSize(25, 25))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setStyleSheet("")
        self.btnClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/icons8-multiply-45.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setIconSize(QtCore.QSize(40, 40))
        self.btnClose.setFlat(True)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout_19.addWidget(self.btnClose)
        self.verticalLayout_18.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame_12 = QtWidgets.QFrame(self.rightsSide_2)
        self.frame_12.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(0, -1, 50, 5)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnChat = QtWidgets.QPushButton(self.frame_12)
        self.btnChat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnChat.setStyleSheet("font: 8pt \"Roboto\";\n"
"color:white;")
        self.btnChat.setFlat(True)
        self.btnChat.setObjectName("btnChat")
        self.horizontalLayout_6.addWidget(self.btnChat)
        self.btnHistory = QtWidgets.QPushButton(self.frame_12)
        self.btnHistory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHistory.setStyleSheet("font: 8pt \"Roboto\";\n"
"color:white;")
        self.btnHistory.setFlat(True)
        self.btnHistory.setObjectName("btnHistory")
        self.horizontalLayout_6.addWidget(self.btnHistory)
        self.btnPlugins = QtWidgets.QPushButton(self.frame_12)
        self.btnPlugins.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlugins.setStyleSheet("font: 8pt \"Roboto\";\n"
"color:white;")
        self.btnPlugins.setFlat(True)
        self.btnPlugins.setObjectName("btnPlugins")
        self.horizontalLayout_6.addWidget(self.btnPlugins)
        self.verticalLayout_18.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.rightsSide_2)
        self.verticalLayout_8.addWidget(self.topBar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("background-color:#F5F5F5;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_9.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.homePage)
        self.frame_3.setStyleSheet("background-color:white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lblAppDetails = QtWidgets.QLabel(self.frame_5)
        self.lblAppDetails.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblAppDetails.setWordWrap(True)
        self.lblAppDetails.setObjectName("lblAppDetails")
        self.verticalLayout_11.addWidget(self.lblAppDetails)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnNext = QtWidgets.QPushButton(self.frame_10)
        self.btnNext.setMinimumSize(QtCore.QSize(20, 0))
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnNext.setStyleSheet("background:white;\n"
"border:2px solid #606268;\n"
"padding:10px;\n"
"font: bold 8pt \"Roboto\";\n"
"color:#606268;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/icons8-more-than-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon1)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_3.addWidget(self.btnNext)
        self.verticalLayout_10.addWidget(self.frame_10, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.homePage)
        self.chatPage = QtWidgets.QWidget()
        self.chatPage.setObjectName("chatPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.chatPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lblQuery = QtWidgets.QLabel(self.chatPage)
        self.lblQuery.setStyleSheet("color:black")
        self.lblQuery.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQuery.setObjectName("lblQuery")
        self.verticalLayout_12.addWidget(self.lblQuery)
        self.frame_4 = QtWidgets.QFrame(self.chatPage)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.chatScroll = QtWidgets.QScrollArea(self.frame_4)
        self.chatScroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatScroll.setWidgetResizable(True)
        self.chatScroll.setObjectName("chatScroll")
        self.chatScrollAreaFrame = QtWidgets.QWidget()
        self.chatScrollAreaFrame.setGeometry(QtCore.QRect(0, 0, 597, 556))
        self.chatScrollAreaFrame.setObjectName("chatScrollAreaFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.chatScrollAreaFrame)
        self.verticalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.chatFrame = QtWidgets.QFrame(self.chatScrollAreaFrame)
        self.chatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatFrame.setObjectName("chatFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.chatFrame)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(15)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_14.addWidget(self.chatFrame, 0, QtCore.Qt.AlignTop)
        self.chatScroll.setWidget(self.chatScrollAreaFrame)
        self.verticalLayout_13.addWidget(self.chatScroll)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.chatArea = QtWidgets.QFrame(self.chatPage)
        self.chatArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chatArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatArea.setObjectName("chatArea")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.chatArea)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtChat = QtWidgets.QLineEdit(self.chatArea)
        self.txtChat.setStyleSheet("background:#F5F5F5;\n"
"border:2px solid #606268;\n"
"padding:4px;\n"
"font:  9pt \"Roboto\";\n"
"color:#343637;\n"
"border-right:none;")
        self.txtChat.setObjectName("txtChat")
        self.horizontalLayout_4.addWidget(self.txtChat)
        self.btnSendMessage = QtWidgets.QPushButton(self.chatArea)
        self.btnSendMessage.setMinimumSize(QtCore.QSize(35, 32))
        self.btnSendMessage.setMaximumSize(QtCore.QSize(35, 32))
        self.btnSendMessage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSendMessage.setStyleSheet("background:#F5F5F5;\n"
"border:2px solid #606268;\n"
"padding:3px;\n"
"font: bold 8pt \"Roboto\";\n"
"color:#606268;\n"
"border-left:none;")
        self.btnSendMessage.setText("")
        self.btnSendMessage.setIcon(icon1)
        self.btnSendMessage.setIconSize(QtCore.QSize(40, 40))
        self.btnSendMessage.setFlat(True)
        self.btnSendMessage.setObjectName("btnSendMessage")
        self.horizontalLayout_4.addWidget(self.btnSendMessage)
        self.verticalLayout_12.addWidget(self.chatArea)
        self.stackedWidget.addWidget(self.chatPage)
        self.historyPage = QtWidgets.QWidget()
        self.historyPage.setObjectName("historyPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.historyPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_13 = QtWidgets.QFrame(self.historyPage)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_20.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.historyScroll = QtWidgets.QScrollArea(self.frame_13)
        self.historyScroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.historyScroll.setWidgetResizable(True)
        self.historyScroll.setObjectName("historyScroll")
        self.historyScrollAreaFrame = QtWidgets.QWidget()
        self.historyScrollAreaFrame.setGeometry(QtCore.QRect(0, 0, 597, 624))
        self.historyScrollAreaFrame.setObjectName("historyScrollAreaFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.historyScrollAreaFrame)
        self.verticalLayout_21.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.histroyFrame = QtWidgets.QFrame(self.historyScrollAreaFrame)
        self.histroyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.histroyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.histroyFrame.setObjectName("histroyFrame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.histroyFrame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_21.addWidget(self.histroyFrame, 0, QtCore.Qt.AlignTop)
        self.historyScroll.setWidget(self.historyScrollAreaFrame)
        self.verticalLayout_20.addWidget(self.historyScroll)
        self.verticalLayout_2.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.historyPage)
        self.pluginPage = QtWidgets.QWidget()
        self.pluginPage.setObjectName("pluginPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pluginPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_18 = QtWidgets.QFrame(self.pluginPage)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_34.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.pluginScroll = QtWidgets.QScrollArea(self.frame_18)
        self.pluginScroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginScroll.setWidgetResizable(True)
        self.pluginScroll.setObjectName("pluginScroll")
        self.pluginScrollAreaFrame = QtWidgets.QWidget()
        self.pluginScrollAreaFrame.setGeometry(QtCore.QRect(0, 0, 597, 624))
        self.pluginScrollAreaFrame.setObjectName("pluginScrollAreaFrame")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.pluginScrollAreaFrame)
        self.verticalLayout_35.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.pluginFrame = QtWidgets.QFrame(self.pluginScrollAreaFrame)
        self.pluginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pluginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginFrame.setObjectName("pluginFrame")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.pluginFrame)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_36.setSpacing(15)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.pluginFrameTemplate = QtWidgets.QFrame(self.pluginFrame)
        self.pluginFrameTemplate.setStyleSheet("background-color:white;")
        self.pluginFrameTemplate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pluginFrameTemplate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginFrameTemplate.setObjectName("pluginFrameTemplate")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.pluginFrameTemplate)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_19 = QtWidgets.QFrame(self.pluginFrameTemplate)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblPluginName = QtWidgets.QLabel(self.frame_19)
        self.lblPluginName.setStyleSheet("color:black;\n"
"font: 87 9pt \"Roboto Black\";")
        self.lblPluginName.setObjectName("lblPluginName")
        self.horizontalLayout_14.addWidget(self.lblPluginName)
        self.btnPluginRemove = QtWidgets.QPushButton(self.frame_19)
        self.btnPluginRemove.setMaximumSize(QtCore.QSize(55, 22))
        self.btnPluginRemove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPluginRemove.setStyleSheet("color:#606268;\n"
"font: 8pt \"Roboto\";")
        self.btnPluginRemove.setFlat(True)
        self.btnPluginRemove.setObjectName("btnPluginRemove")
        self.horizontalLayout_14.addWidget(self.btnPluginRemove, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_37.addWidget(self.frame_19)
        self.lblPluginMessage = QtWidgets.QLabel(self.pluginFrameTemplate)
        self.lblPluginMessage.setStyleSheet("font: 8pt \"Roboto\";\n"
"color:black;")
        self.lblPluginMessage.setWordWrap(True)
        self.lblPluginMessage.setObjectName("lblPluginMessage")
        self.verticalLayout_37.addWidget(self.lblPluginMessage)
        self.verticalLayout_36.addWidget(self.pluginFrameTemplate)
        self.btnAddPlugin = QtWidgets.QPushButton(self.pluginFrame)
        self.btnAddPlugin.setMinimumSize(QtCore.QSize(20, 0))
        self.btnAddPlugin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddPlugin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnAddPlugin.setStyleSheet("background:#F5F5F5;\n"
"border:2px solid #606268;\n"
"padding:4px;\n"
"font:  9pt \"Roboto\";\n"
"color:#343637;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/icons8-plus-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddPlugin.setIcon(icon2)
        self.btnAddPlugin.setIconSize(QtCore.QSize(25, 25))
        self.btnAddPlugin.setObjectName("btnAddPlugin")
        self.verticalLayout_36.addWidget(self.btnAddPlugin)
        self.chatArea_2 = QtWidgets.QFrame(self.pluginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatArea_2.sizePolicy().hasHeightForWidth())
        self.chatArea_2.setSizePolicy(sizePolicy)
        self.chatArea_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.chatArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatArea_2.setObjectName("chatArea_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.chatArea_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_36.addWidget(self.chatArea_2)
        self.verticalLayout_35.addWidget(self.pluginFrame, 0, QtCore.Qt.AlignTop)
        self.pluginScroll.setWidget(self.pluginScrollAreaFrame)
        self.verticalLayout_34.addWidget(self.pluginScroll)
        self.verticalLayout_5.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.pluginPage)
        self.modelPage = QtWidgets.QWidget()
        self.modelPage.setObjectName("modelPage")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.modelPage)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.frame_22 = QtWidgets.QFrame(self.modelPage)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_40.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.modelScroll = QtWidgets.QScrollArea(self.frame_22)
        self.modelScroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modelScroll.setWidgetResizable(True)
        self.modelScroll.setObjectName("modelScroll")
        self.modelScrollAreaFrame = QtWidgets.QWidget()
        self.modelScrollAreaFrame.setGeometry(QtCore.QRect(0, 0, 597, 624))
        self.modelScrollAreaFrame.setObjectName("modelScrollAreaFrame")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.modelScrollAreaFrame)
        self.verticalLayout_41.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.modelFrame = QtWidgets.QFrame(self.modelScrollAreaFrame)
        self.modelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modelFrame.setObjectName("modelFrame")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.modelFrame)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_42.setSpacing(15)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.verticalLayout_41.addWidget(self.modelFrame, 0, QtCore.Qt.AlignTop)
        self.btnAddModel = QtWidgets.QPushButton(self.modelScrollAreaFrame)
        self.btnAddModel.setMinimumSize(QtCore.QSize(20, 0))
        self.btnAddModel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddModel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnAddModel.setStyleSheet("background:#F5F5F5;\n"
"border:2px solid #606268;\n"
"padding:4px;\n"
"font:  9pt \"Roboto\";\n"
"color:#343637;\n"
"")
        self.btnAddModel.setIcon(icon2)
        self.btnAddModel.setIconSize(QtCore.QSize(25, 25))
        self.btnAddModel.setObjectName("btnAddModel")
        self.verticalLayout_41.addWidget(self.btnAddModel)
        self.modelScroll.setWidget(self.modelScrollAreaFrame)
        self.verticalLayout_40.addWidget(self.modelScroll)
        self.verticalLayout_44.addWidget(self.frame_22)
        self.stackedWidget.addWidget(self.modelPage)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_47.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.frame_24 = QtWidgets.QFrame(self.page_5)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_24.setStyleSheet("background-color:white;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_46.setContentsMargins(5, 5, 5, -1)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.btnScriptRemove = QtWidgets.QPushButton(self.frame_25)
        self.btnScriptRemove.setMaximumSize(QtCore.QSize(55, 22))
        self.btnScriptRemove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnScriptRemove.setStyleSheet("color:#606268;\n"
"font: 8pt \"Roboto\";")
        self.btnScriptRemove.setFlat(True)
        self.btnScriptRemove.setObjectName("btnScriptRemove")
        self.verticalLayout_46.addWidget(self.btnScriptRemove, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.lblScriptError = QtWidgets.QLabel(self.frame_25)
        self.lblScriptError.setMinimumSize(QtCore.QSize(0, 140))
        self.lblScriptError.setText("")
        self.lblScriptError.setPixmap(QtGui.QPixmap(":/images/images/scriptbroken.png"))
        self.lblScriptError.setScaledContents(False)
        self.lblScriptError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblScriptError.setObjectName("lblScriptError")
        self.verticalLayout_46.addWidget(self.lblScriptError, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_45.addWidget(self.frame_25)
        self.verticalLayout_47.addWidget(self.frame_24)
        self.frame_26 = QtWidgets.QFrame(self.page_5)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_47.addWidget(self.frame_26)
        self.stackedWidget.addWidget(self.page_5)
        self.SpecificHistoryPage = QtWidgets.QWidget()
        self.SpecificHistoryPage.setObjectName("SpecificHistoryPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SpecificHistoryPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.SpecificHistoryPage)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_23.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.specifcHistoryScroll = QtWidgets.QScrollArea(self.frame_14)
        self.specifcHistoryScroll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.specifcHistoryScroll.setWidgetResizable(True)
        self.specifcHistoryScroll.setObjectName("specifcHistoryScroll")
        self.historyScrollAreaFrame_2 = QtWidgets.QWidget()
        self.historyScrollAreaFrame_2.setGeometry(QtCore.QRect(0, 0, 597, 624))
        self.historyScrollAreaFrame_2.setObjectName("historyScrollAreaFrame_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.historyScrollAreaFrame_2)
        self.verticalLayout_24.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.specificHistoryFrame = QtWidgets.QFrame(self.historyScrollAreaFrame_2)
        self.specificHistoryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.specificHistoryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.specificHistoryFrame.setObjectName("specificHistoryFrame")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.specificHistoryFrame)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24.addWidget(self.specificHistoryFrame, 0, QtCore.Qt.AlignTop)
        self.specifcHistoryScroll.setWidget(self.historyScrollAreaFrame_2)
        self.verticalLayout_23.addWidget(self.specifcHistoryScroll)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.SpecificHistoryPage)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.appMargins.addWidget(self.bg)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome Page"))
        self.btnModel.setText(_translate("MainWindow", "No Model Selected"))
        self.btnClose.setToolTip(_translate("MainWindow", "Close"))
        self.btnChat.setText(_translate("MainWindow", "Chat"))
        self.btnHistory.setText(_translate("MainWindow", "History"))
        self.btnPlugins.setText(_translate("MainWindow", "Plugins"))
        self.lblAppDetails.setText(_translate("MainWindow", "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <style>\n"
"        body {\n"
"            font-size: 10.75px;\n"
"            color: #343637;\n"
"            font-family: \'Roboto\', sans-serif; /* Add Roboto regular font */\n"
"        }\n"
"        p, ol, li {\n"
"            font-family: \'Roboto\', sans-serif; /* Add Roboto regular font */\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <p style=\"margin-bottom: 30px; color: #AD00BE;font-family: \'Roboto Black\', sans-serif;\">Welcome!</p>\n"
"    <p ><span style=\"color: #AD00BE;font-family: \'Roboto Black\', sans-serif;\">Chat with Confidence:</span> You\'re connected to the StableLM Zephyr 3b-GGUF.</p>\n"
"    <p >To switch models:</p>\n"
"    <ol>\n"
"        <li>Click on StableLM Zephyr 3B-GGUF at the top of your chat.</li>\n"
"        <li>Provide the location of your new GGUF file when prompted.</li>\n"
"    </ol>\n"
"    <p><span style=\"color: #AD00BE;font-family: \'Roboto Black\', sans-serif;\">Expand Your Horizons:</span> To add new capabilities:</p>\n"
"    <ol>\n"
"        <li>Explore the Plugins tab.</li>\n"
"        <li>Choose an option to add a plugin and enhance your chat experience.</li>\n"
"    </ol>\n"
"    <p><span style=\"color: #AD00BE;font-family: \'Roboto Black\', sans-serif;\">Revisit Conversations:</span> The History tab stores all your previous chats, <br> including communications from your added plugins, ensuring you never miss <br> a beat.</p>\n"
"</body>\n"
"</html>\n"
""))
        self.btnNext.setText(_translate("MainWindow", "NEXT                           "))
        self.lblQuery.setText(_translate("MainWindow", "Send your query!!!"))
        self.txtChat.setPlaceholderText(_translate("MainWindow", "Start Chat..."))
        self.btnSendMessage.setToolTip(_translate("MainWindow", "Close"))
        self.lblPluginName.setText(_translate("MainWindow", "Script Sage Writing"))
        self.btnPluginRemove.setText(_translate("MainWindow", "Remove"))
        self.lblPluginMessage.setText(_translate("MainWindow", "Elevate your writing instantly with Script Sage, utilizing the power of your..."))
        self.btnAddPlugin.setText(_translate("MainWindow", "Add Plugin                                                                                                "))
        self.btnAddModel.setText(_translate("MainWindow", "Add Model                                                                                                "))
        self.btnScriptRemove.setText(_translate("MainWindow", "Remove"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
